// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaxghnqyvvdgnvrhchjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheGdobnF5dnZkZ252cmhjaGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTE5MjAsImV4cCI6MjA1OTU4NzkyMH0.Smna4n03YNSZGdkmmkc8JuhISGCNsIttA--pyWTrGLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);